export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const USER_LOADED = "USER_LOADED";
export const DASHBOARD_DETAILS = "DASHBOARD_DETAILS";
export const DASHBOARD_ORDER_DETAILS = "DASHBOARD_ORDER_DETAILS";
export const DASHBOARD_USER_DETAILS = "DASHBOARD_USER_DETAILS";
export const GET_DASHBOARD_DELIVERY = "GET_DASHBOARD_DELIVERY";

export const CAREER_DETAILS = "CAREER_DETAILS";
export const ADD_CAREER = "ADD_CAREER";
export const DELETE_CAREER = "DELETE_CAREER";


export const NEW_ARRIVAL = "NEW_ARRIVAL";
export const GET_PAGES_DETAILS = "GET_PAGES_DETAILS";

export const GET_ORDERS = "GET_ORDERS";

export const GET_PRODUCTS = "GET_PRODUCTS";

export const GET_INSTRUCTION_DATA = "GET_INSTRUCTION_DATA";
export const GET_INSTRUCTION_LANGUAGE = "GET_INSTRUCTION_LANGUAGE";


export const GET_PICKLIST_DATA = "GET_PICKLIST_DATA";

export const GET_POLICY_DATA = "GET_POLICY_DATA";
